services:
  server:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - mysql
  mysql:
    image: mysql
    ports:
      - 7999:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_USER=gsd-dev 
      - MYSQL_PASSWORD=password 
      - MYSQL_DATABASE=gsd
volumes:
  logvolume01: {}